### ISSUE TITLE
The project is dead? Or is it supported elsewhere?

### ISSUE THREAD

**Issue by wdammak** [ogunsakin01/TravelPortal#3]
The project is dead? Or is it supported elsewhere?
Several menus that don't work because it lacks their controllers / views ...

**Comment by ogunsakin01** [comment]
Currently, I had to hold back development here because of privacy and security issues.
But I ll be happy to provide support if you are working on a similar project.

**Comment by wdammak** [comment]
Too bad you made a good start to the project, but it seems that you have dropped half way!
